export const BgClass = {
  Bug: 'bg-pokemon-bug',
  Dark: 'bg-pokemon-dark',
  Dragon: 'bg-pokemon-dragon',
  Electric: 'bg-pokemon-electric',
  Fairy: 'bg-pokemon-fairy',
  Fighting: 'bg-pokemon-fighting',
  Fire: 'bg-pokemon-fire',
  Flying: 'bg-pokemon-flying',
  Ghost: 'bg-pokemon-ghost',
  Grass: 'bg-pokemon-grass',
  Ground: 'bg-pokemon-ground',
  Ice: 'bg-pokemon-ice',
  Normal: 'bg-pokemon-normal',
  Poison: 'bg-pokemon-poison',
  Psychic: 'bg-pokemon-psychic',
  Rock: 'bg-pokemon-rock',
  Steel: 'bg-pokemon-steel',
  Water: 'bg-pokemon-water',
} as const;

export const FromClass = {
  Bug: 'from-pokemon-bug/40',
  Dark: 'from-pokemon-dark/40',
  Dragon: 'from-pokemon-dragon/40',
  Electric: 'from-pokemon-electric/40',
  Fairy: 'from-pokemon-fairy/40',
  Fighting: 'from-pokemon-fighting/40',
  Fire: 'from-pokemon-fire/40',
  Flying: 'from-pokemon-flying/40',
  Ghost: 'from-pokemon-ghost/40',
  Grass: 'from-pokemon-grass/40',
  Ground: 'from-pokemon-ground/40',
  Ice: 'from-pokemon-ice/40',
  Normal: 'from-pokemon-normal/40',
  Poison: 'from-pokemon-poison/40',
  Psychic: 'from-pokemon-psychic/40',
  Rock: 'from-pokemon-rock/40',
  Steel: 'from-pokemon-steel/40',
  Water: 'from-pokemon-water/40',
} as const;

export const ToClass = {
  Bug: 'to-pokemon-bug/40',
  Dark: 'to-pokemon-dark/40',
  Dragon: 'to-pokemon-dragon/40',
  Electric: 'to-pokemon-electric/40',
  Fairy: 'to-pokemon-fairy/40',
  Fighting: 'to-pokemon-fighting/40',
  Fire: 'to-pokemon-fire/40',
  Flying: 'to-pokemon-flying/40',
  Ghost: 'to-pokemon-ghost/40',
  Grass: 'to-pokemon-grass/40',
  Ground: 'to-pokemon-ground/40',
  Ice: 'to-pokemon-ice/40',
  Normal: 'to-pokemon-normal/40',
  Poison: 'to-pokemon-poison/40',
  Psychic: 'to-pokemon-psychic/40',
  Rock: 'to-pokemon-rock/40',
  Steel: 'to-pokemon-steel/40',
  Water: 'to-pokemon-water/40',
} as const;

export type BgClass = (typeof BgClass)[keyof typeof BgClass];
export type FromClass = (typeof FromClass)[keyof typeof FromClass];
export type ToClass = (typeof ToClass)[keyof typeof ToClass];
