export const VERSION_GROUP = 'firered-leafgreen';

export const MAX_PID = 386;

export const categoryMap = {
  water: 'Special',
  grass: 'Special',
  fire: 'Special',
  ice: 'Special',
  electric: 'Special',
  psychic: 'Special',
  dragon: 'Special',
  dark: 'Special',

  fighting: 'Physical',
  poison: 'Physical',
  ground: 'Physical',
  flying: 'Physical',
  bug: 'Physical',
  rock: 'Physical',
  ghost: 'Physical',
  steel: 'Physical',
  fairy: 'Physical',
  normal: 'Physical',
};

export const TMMap = {
  真氣拳: '01',
  龍爪: '02',
  水之波動: '03',
  冥想: '04',
  吼叫: '05',
  劇毒: '06',
  冰雹: '07',
  健美: '08',
  種子機關槍: '09',
  覺醒力量: '10',
  大晴天: '11',
  挑釁: '12',
  冰凍光束: '13',
  暴風雪: '14',
  破壞光線: '15',
  光牆: '16',
  守住: '17',
  求雨: '18',
  終極吸取: '19',
  神秘守護: '20',
  遷怒: '21',
  日光束: '22',
  鐵尾: '23',
  十萬伏特: '24',
  打雷: '25',
  地震: '26',
  報恩: '27',
  挖洞: '28',
  精神強念: '29',
  暗影球: '30',
  劈瓦: '31',
  影子分身: '32',
  反射壁: '33',
  電擊波: '34',
  噴射火焰: '35',
  污泥炸彈: '36',
  沙暴: '37',
  大字爆炎: '38',
  岩石封鎖: '39',
  燕返: '40',
  無理取鬧: '41',
  硬撐: '42',
  秘密之力: '43',
  睡覺: '44',
  迷人: '45',
  小偷: '46',
  鋼翼: '47',
  特性互換: '48',
  搶奪: '49',
  過熱: '50',

  居合斬: '秘傳01',
  飛翔: '秘傳02',
  衝浪: '秘傳03',
  怪力: '秘傳04',
  閃光: '秘傳05',
  碎岩: '秘傳06',
  攀瀑: '秘傳07',
};
